### ISSUE TITLE
On-prem enviroment

### ISSUE THREAD

**Issue by franrebo84** [plutomi/plutomi#576]
Hello! I think this project is great!
I was wondering if there is any way to deploy this in an on-premises environment using docker.

Thanks!

**Comment by joswayski** [comment]
Hey sorry for the late reply!

Due to the  dependency on AWS tools like Dynamo, Event Bridge & Step Functions, it is not possible to run everything on prem in Docker :( 

![image](https://user-images.githubusercontent.com/22891173/164997426-a3c05828-f81c-4bee-a57a-423447924150.png)

You could run the main site + API (it's NextJS & Express) but not the asynchronous tasks & DB.
